refactor - решение по ТЗ спринта 9
bREDMACHINE/java-filmorate pull request #2
Opened 2022-06-18 20:20 UTC by bREDMACHINE

2022-06-19 09:08 UTC, TyutterinYakov requested changes
Добрый день! Отметил то, что следует исправить) Хорошего дня! Если возникнут вопросы - пиши в слак, буду рад помочь🤩

2022-06-19 09:08 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage inMemoryFilmStorage;
Уровень контроллера не должен общаться напрямую с уровнем хранилища. Он это делает через прослойку в виде сервиса

2022-06-19 09:08 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserStorage inMemoryUserStorage;
Уровень контроллера не должен общаться напрямую с уровнем хранилища. Он это делает через прослойку в виде сервиса

2022-06-19 09:08 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getTopFilms(@RequestParam(required = false) String count) {
Так как у тебя используется .limit(), если в него передать отрицательное значение, возникнет ошибка. Для того, чтобы на вход поступало только корректное значение, следует принимать не ссылочный тип(String), а примитив(int). А, во-вторых, следует перед параметров поставить аннотацию [@Positive](https://github.com/positive), а над классом контроллера навесить аннотацию [@Validated](https://github.com/Validated), таким образом перед передачей значения в метод, оно будет проверяться на соответствие, если оно не будет удовлетворять условию, будет выброшена ошибка валидации и обработана, а статус вернется красивым(400 BAD_REQUEST), а для красивого ответа от сервера нужно использовать еще один обработчик
[@ExceptionHandler](https://github.com/ExceptionHandler)
public ResponseEntity<?> exc(ConstraintViolationException ex){
return new ResponseEntity<>(ex.getMessage(), HttpStatus.BAD_REQUEST);
}
Кстати, в RequestParam можно указать параметр defaultValue = "10", таким образом, когда ничего не будет передано - значение будет равно 10

2022-06-19 09:08 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Map<String, String> handleRuntimeException(final RuntimeException e) {
Этот статус должет быть у исключений Throwable, то есть у всех, что не имеют обработки

2022-06-19 09:08 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Map<String, String> handleNullPointerException(final NullPointerException e) {
NPE мы не обрабатываем. Это не является хорошей практикой. Для отсутствующий элементов следует выбрасывать свое кастомное непроверяемое исключение, когда объект не найден

2022-06-19 09:08 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @ExceptionHandler
Аналогично

2022-06-19 09:08 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @ExceptionHandler
аналогично, как и в другом контроллере

2022-06-19 09:08 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @ExceptionHandler
Так же следует вынести все обработчики в отдельный класс с аннотацией @ControllerAdvice, они не должны находиться с основными мапингами

2022-06-19 09:08 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> getTopFilms(String countSting) {
принимать следует числовое значение, Spring сам преобразует значение за нас)

2022-06-19 09:08 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public Film getFilm(long id) {
Хорошо было бы использовать в методах получения по идентификатору тип Optional https://habr.com/ru/post/346782/ Гарантирую, ты не пожалеешь, а заодно в будущем тебе будет проще, так как он активно используется при работе со Spring Data

2022-06-19 09:08 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new NullPointerException("указанный ID не существует");
Для отсутствующего объекта нужно написать свой класс-исключение, которое должно быть непроверяемым, NPE для этого не подходит

2022-06-19 09:08 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +            throw new NullPointerException("указанный ID не существует");
Для отсутствующего объекта нужно написать свой класс-исключение, которое должно быть непроверяемым, NPE для этого не подходит

2022-06-19 09:08 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage {
Всю валидацию и выбросы исключений следует вынести на уровень сервиса. Хранилище не должно этим заниматься. Оно сохраняет новый объект и устанавливает ему идентификатор, обновляет объект, удаляет объект, отдает вс объекты

2022-06-19 09:08 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +public class InMemoryUserStorage implements UserStorage {
Всю валидацию и выбросы исключений следует вынести на уровень сервиса. Хранилище не должно этим заниматься. Оно сохраняет новый объект и устанавливает ему идентификатор, обновляет объект, удаляет объект, отдает вс объекты

2022-06-19 09:08 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +
Если будешь использовать тип Optional, то здесь как раз будет проверка, можно будет использовать простую лямбду .orElseThrow(() -> new NotFoundExcetion(...)); То есть, если объект не будет найден, будет выброшено исключение, а если он есть, мы просто его получим, как будто написали .get()
Это для метода получения по идентификатору, к которому, кстати, можно потом обращаться, чтобы не дублировать строку с выбросом исключения)

2022-06-19 09:08 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +
Если будешь использовать тип Optional, то здесь как раз будет проверка, можно будет использовать простую лямбду .orElseThrow(() -> new NotFoundExcetion(...)); То есть, если объект не будет найден, будет выброшено исключение, а если он есть, мы просто его получим, как будто написали .get()
Это для метода получения по идентификатору, к которому, кстати, можно потом обращаться, чтобы не дублировать строку с выбросом исключения)

2022-06-19 09:08 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public static boolean isNumeric(String str) {
И от этого метода можно будет избавиться)

2022-06-19 16:11 UTC, bREDMACHINE commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage inMemoryFilmStorage;
Исправил, жаль, что в задании об этом не говорится.

2022-06-19 16:12 UTC, bREDMACHINE commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserStorage inMemoryUserStorage;
Исправил, жаль, что в задании об этом не говорится.

2022-06-21 16:56 UTC, bREDMACHINE commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Map<String, String> handleNullPointerException(final NullPointerException e) {
Исправил.

2022-06-21 16:56 UTC, bREDMACHINE commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Map<String, String> handleRuntimeException(final RuntimeException e) {
Я плаваю в исключениях, хотя читал теорию и у Яндекса и в интернетах про них уже много раз. Указал Throwable, но почему должен быть он мне лично не ясно и найти про это что-либо почитать я не смог.

2022-06-21 16:56 UTC, bREDMACHINE commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getTopFilms(@RequestParam(required = false) String count) {
Исправил. надеюсь правильно сделал. Снова хотел в классах film и user расставить аннотации для валидации (как было предложено в 8 ТЗ), но второй раз уже переписываю код и никак не пойму как мне проходить тесты для валидации. И самое главное - валидация даты релиза фильма.

2022-06-21 16:56 UTC, bREDMACHINE commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @ExceptionHandler
Исправил.

2022-06-21 16:56 UTC, bREDMACHINE commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @ExceptionHandler
Исправил.

2022-06-21 16:57 UTC, bREDMACHINE commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @ExceptionHandler
Исправил.

2022-06-21 16:57 UTC, bREDMACHINE commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> getTopFilms(String countSting) {
Исправил.

2022-06-21 17:00 UTC, bREDMACHINE commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public Film getFilm(long id) {
Исправил. Получилось очень круто. Нам не давали такое применение, что можно обернуть внутри метода другой метод в Optional и тут же получить значение. Яндекс в теории давал про методы, которые возвращают Optional, которые потом нужно проверить на наличие объекта внутри и так далее. Сильно увеличивает количество кода.

2022-06-21 17:00 UTC, bREDMACHINE commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new NullPointerException("указанный ID не существует");
Исправил, надеюсь правильно.

2022-06-21 17:01 UTC, bREDMACHINE commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +            throw new NullPointerException("указанный ID не существует");
Написал свое исключение, метод теперь лишний.

2022-06-21 17:01 UTC, bREDMACHINE commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage {
Исправил

2022-06-21 17:02 UTC, bREDMACHINE commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +public class InMemoryUserStorage implements UserStorage {
Исправил

2022-06-21 17:02 UTC, bREDMACHINE commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +
Да, все получилось

2022-06-21 17:03 UTC, bREDMACHINE commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +
Исправил

2022-06-21 17:03 UTC, bREDMACHINE commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public static boolean isNumeric(String str) {
От метода избавился

2022-06-21 17:09 UTC, bREDMACHINE commented
Устранил замечания

2022-06-21 19:12 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Map<String, String> handleRuntimeException(final RuntimeException e) {
Он находится на вершине, а значит, если исключение не будет перехвачено(не имеет обработчика), значит оно пойдет в этот обработчик, так как он обрабатывает вообще любые ошибки

2022-06-21 19:19 UTC, TyutterinYakov reviewed
Добрый вечер! Остаются мелкие недочеты) Жду на финальное ревью :)

2022-06-21 19:19 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public boolean isValidation(Film film) {
Так как метод используется для внутренней реализации класса, следует сделать его приватным

2022-06-21 19:19 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public boolean isValidation(User user) {
Так как метод используется для внутренней реализации класса, следует сделать его приватным

2022-06-21 19:19 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return Optional.ofNullable(inMemoryUserStorage.getUser(id))
Это должно выглядеть примерно так:
inMemoryUserStorage.getUser(id).orElseThrow(() -> new NotFoundException("указанный ID не существует"));
То есть из хранилища должен приходить тип Optional, не здесь мы должны в него оборачивать

2022-06-21 19:19 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return Optional.ofNullable(inMemoryFilmStorage.getFilm(id))
Это должно выглядеть примерно так:
inMemoryUserStorage.getUser(id).orElseThrow(() -> new NotFoundException("указанный ID не существует"));
То есть из хранилища должен приходить тип Optional, не здесь мы должны в него оборачивать

2022-06-21 19:19 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public Film getFilm(long id) {
Метод должен возвращать Optional, а в методе в сервисе уже следует выбрасывать исключение или доставать объект)

2022-06-21 19:19 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    public User getUser(long id) {
Метод должен возвращать Optional, а в методе в сервисе уже следует выбрасывать исключение или доставать объект)

2022-06-22 11:12 UTC, bREDMACHINE commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public boolean isValidation(Film film) {
исправил

2022-06-22 11:12 UTC, bREDMACHINE commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public boolean isValidation(User user) {
исправил

2022-06-22 11:16 UTC, bREDMACHINE commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return Optional.ofNullable(inMemoryUserStorage.getUser(id))
Я поправил, но прежний вариант был очень интересный.

2022-06-22 11:17 UTC, bREDMACHINE commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return Optional.ofNullable(inMemoryFilmStorage.getFilm(id))
Поправил

2022-06-22 11:17 UTC, bREDMACHINE commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public Film getFilm(long id) {
все переделал

2022-06-22 11:17 UTC, bREDMACHINE commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    public User getUser(long id) {
исправил

2022-06-22 11:41 UTC, bREDMACHINE commented
Исправил

2022-06-22 12:11 UTC, bREDMACHINE commented
Добавил аннотации для валидации. Только с релизом фильма не нашел подходящую.

2022-06-22 17:00 UTC, TyutterinYakov approved these changes
Ну что, поздравляю с успешной сдачей спринта :) Сил и терпения на пути к цели! Пример кастомной аннотации для валидации есть в конце этого вопроса https://stackoverflow.com/questions/44376401/validating-date-with-spring-boot-or-hibernate-validator Хорошего вечера!🐝

2022-06-23 07:33 UTC, merged